### ISSUE TITLE
NextChat和OpenCat都不能用

### ISSUE THREAD

**Issue by Luo-hongyi** [RipperTs/poe2openai#1]
![image](https://github.com/user-attachments/assets/e3b95edf-cd2f-4988-b34b-37eeb75d4fa0)

**Comment by RipperTs** [comment]
看起来流式输出结果是正常的，不过未对一些前端项目做适配。
在 [new-api](https://github.com/Calcium-Ion/new-api) 项目上使用是正常的。

晚点我看下为什么结构解析不出来

**Comment by RipperTs** [comment]
已修复

**Comment by Luo-hongyi** [comment]
刚pull的在NextChat可以用了👍🏻

想问一下new_api里怎样设置？

![image](https://github.com/user-attachments/assets/1ed2577d-8166-48b4-93e0-1431d41c4a2f)
![image](https://github.com/user-attachments/assets/8e7f561c-e077-49b8-9c76-b009c6116fd8)

**Comment by RipperTs** [comment]
直接填写域名即可，例如： `http://127.0.0.1:9881`  
秘钥填写 poe 的 api key
自定义模型就填 poe 的机器人名称即可，例如： `GPT-3.5-Turbo` **注意大小写**

**Comment by Luo-hongyi** [comment]
connect: connection refused

有没有CORS问题？
